# Generated by Django 5.1.3 on 2024-11-28 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.OneToOneField(
                null=True,  # Allow NULL values for existing records
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='courier',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
