# Generated by Django 5.1.3 on 2024-11-30 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_alter_courier_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='user',
            field=models.OneToOneField(
                default=6,  # Replace <DEFAULT_USER_ID> with the ID from the shell
                on_delete=models.CASCADE,
                related_name='courier_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
